from pydantic import BaseModel, Field
from typing import List


class ComputeFactorExposuresOutput(BaseModel):
    """Pydantic model for compute_factor_exposures node outputs."""
    factor_names: List[str] = (
        Field(..., description="List of all factor names computed for each security-day")
    )
    factor_calculation_descriptions: List[str] = (
        Field(..., description="For each factor, a brief description of the calculation method (e.g., ratio, ranking)")
    )
    factor_column_schema: str = (
        Field(..., description="Text representation of the table schema for the factor columns (e.g., \"factor_name: float, calculation: str\")")
    )
    total_factor_columns: int = (
        Field(..., description="Total number of factor columns generated across all securities and dates")
    )


class TestFactorPerformanceOutput(BaseModel):
    """Pydantic model for test_factor_performance node outputs."""
    factor_names: List[str] = (
        Field(..., description="List of factor names evaluated")
    )
    avg_t_stats: List[float] = (
        Field(..., description="Average t\u2011statistic from cross\u2011sectional regressions for each factor")
    )
    annualized_sharpe: List[float] = (
        Field(..., description="Annualized Sharpe ratio derived from factor regression predictive power")
    )
    p_values: List[float] = (
        Field(..., description="P\u2011value of the factor coefficient in the regression")
    )
    is_significant: List[bool] = (
        Field(..., description="True if p\u2011value < 0.05, indicating statistical significance")
    )


def test_factor_performance(compute_factor_exposures_input: ComputeFactorExposuresOutput, **kwargs) -> TestFactorPerformanceOutput:
    """
    Evaluate historical predictive performance of each individual factor by
    running cross-sectional regressions of next-day stock returns on factor
    exposures. Returns summary statistics including average t-statistics,
    annualized Sharpe ratios, p-values, and significance flags.

    Parameters
    ----------
    factor_names : List[str]
        List of factor names computed for each security-day, as generated by
        compute_factor_exposures.
    factor_exposures : Dict[str, List[float]]
        Mapping from factor names to their exposure values for each
        security-day across the dataset.
    next_day_returns : List[float]
        List or array of next-day stock returns for each security-day
        observation, aligned with factor exposures.

    Returns
    -------
    Dict[str, List]
        A dictionary containing performance metrics per factor:
        'factor_names' (List[str]), 'avg_t_stats' (List[float]),
        'annualized_sharpe' (List[float]), 'p_values' (List[float]), and
        'is_significant' (List[bool]) indicating statistical significance.

    Raises
    ------
    ValueError
        If factor exposures or returns are missing, misaligned, or empty.
    RuntimeError
        If regression fitting fails for any factor due to data issues.

    Examples
    --------
    >>> factor_names = ['momentum', 'value']
    >>> factor_exposures = {
    ...     'momentum': [0.1, 0.2, -0.1, 0.05],
    ...     'value': [0.5, 0.3, 0.1, -0.2]
    >>> }
    >>> next_day_returns = [0.02, 0.03, -0.01, 0.0]
    >>> results = test_factor_performance(factor_names, factor_exposures,
    next_day_returns)
    {'factor_names': ['momentum', 'value'],
     'avg_t_stats': [2.5, 1.1],
     'annualized_sharpe': [1.3, 0.7],
     'p_values': [0.015, 0.28],
     'is_significant': [True, False]}

    >>> factor_names = ['quality']
    >>> factor_exposures = {'quality': [0.2, 0.4, 0.3]}
    >>> next_day_returns = [0.01, 0.02, 0.015]
    >>> results = test_factor_performance(factor_names, factor_exposures,
    next_day_returns)
    {'factor_names': ['quality'],
     'avg_t_stats': [3.2],
     'annualized_sharpe': [1.6],
     'p_values': [0.005],
     'is_significant': [True]}

    """
    return TestFactorPerformanceOutput(
        factor_names=[],
        avg_t_stats=[],
        annualized_sharpe=[],
        p_values=[],
        is_significant=[],
    )