from pydantic import BaseModel, Field
from typing import List


class ComputeFactorExposuresOutput(BaseModel):
    """Pydantic model for compute_factor_exposures node outputs."""
    factor_names: List[str] = (
        Field(..., description="List of all factor names computed for each security-day")
    )
    factor_calculation_descriptions: List[str] = (
        Field(..., description="For each factor, a brief description of the calculation method (e.g., ratio, ranking)")
    )
    factor_column_schema: str = (
        Field(..., description="Text representation of the table schema for the factor columns (e.g., \"factor_name: float, calculation: str\")")
    )
    total_factor_columns: int = (
        Field(..., description="Total number of factor columns generated across all securities and dates")
    )


class SelectSignificantFactorsOutput(BaseModel):
    """Pydantic model for select_significant_factors node outputs."""
    selected_factors: List[str] = (
        Field(..., description="Names of factors that met the significance criteria (p-value < 0.05 and positive average t-statistic). Each name represents one factor.")
    )
    significant_factor_count: int = (
        Field(..., description="Total number of factors that passed the significance thresholds.")
    )
    is_valid_selection: bool = (
        Field(..., description="Indicates whether the selection process completed without errors and produced at least one significant factor.")
    )


class MergeCleanedDataOutput(BaseModel):
    """Pydantic model for merge_cleaned_data node outputs."""
    total_rows: int = (
        Field(..., description="Total number of security\u2011day observations in the merged dataset.")
    )
    total_columns: int = (
        Field(..., description="Total number of columns (features) in the merged dataset, including identifier, date, price, fundamental, and alternative fields.")
    )
    column_names: List[str] = (
        Field(..., description="List of all column names present in the merged dataset.")
    )
    is_successful: bool = (
        Field(..., description="Flag indicating whether the merge operation completed without errors.")
    )
    merge_summary: str = (
        Field(..., description="Short textual summary of the merge operation, e.g., \"Merged 5,000 securities over 2,500 trading days with 120 columns.\"")
    )


class TrainRandomForestModelOutput(BaseModel):
    """Pydantic model for train_random_forest_model node outputs."""
    model_name: str = (
        Field(..., description="Identifier for the trained model instance")
    )
    n_estimators: int = (
        Field(..., description="Number of trees in the random forest")
    )
    max_depth: int = (
        Field(..., description="Maximum depth of each tree (default if not specified)")
    )
    oob_r_squared: float = (
        Field(..., description="Out\u2011of\u2011bag R\u2011squared score for model performance")
    )
    feature_importances: List[float] = (
        Field(..., description="Relative importance scores for each selected factor in the model")
    )
    num_training_samples: int = (
        Field(..., description="Count of samples used in the training set")
    )
    num_selected_factors: int = (
        Field(..., description="Number of factor features included in the model")
    )


def train_random_forest_model(compute_factor_exposures_input: ComputeFactorExposuresOutput, select_significant_factors_input: SelectSignificantFactorsOutput, merge_cleaned_data_input: MergeCleanedDataOutput, **kwargs) -> TrainRandomForestModelOutput:
    """
    Train a random forest regressor to predict next-day excess returns using
    selected factor exposures as features. The model uses 500 trees with default
    tree depth, employing out-of-bag samples to estimate R-squared performance.

    Parameters
    ----------
    factor_exposures : DataFrame
        Table including numerical exposures for each security-day and
        factor, generated by compute_factor_exposures.
    selected_factors : List[str]
        List of factor names that passed significance thresholds (from
        select_significant_factors) used as features.
    merged_data : DataFrame
        Unified dataset merging cleaned price, fundamental, and alternative
        data to align features with target returns.
    next_day_returns : Series or array-like
        Target variable: next-day excess returns corresponding to each
        security-day in the training period.

    Returns
    -------
    dict
        A dictionary containing trained model summary and metrics:
        model_name (str), n_estimators (int), max_depth (int or None),
        oob_r_squared (float), feature_importances (List[float]),
        num_training_samples (int), num_selected_factors (int).

    Raises
    ------
    ValueError
        If there are no selected factors or if input datasets have
        mismatched indices or insufficient data for training.
    RuntimeError
        If the random forest training process fails or OOB estimation is not
        available.

    Examples
    --------
    >>> # Assume factor_exposures is a DataFrame indexed by security-day,
    >>> # selected_factors is a list of factor names to use as features,
    >>> # merged_data contains joined cleaned data, and next_day_returns is
    aligned target.
    >>> result = train_random_forest_model(factor_exposures, selected_factors,
    merged_data, next_day_returns)
    >>> print(result['model_name'], result['oob_r_squared'],
    len(result['feature_importances']))
    RandomForest_500trees 0.25 10

    >>> # Using a smaller factor subset
    >>> result = train_random_forest_model(factor_exposures, ['momentum',
    'value'], merged_data, next_day_returns)
    >>> print(f"Model: {result['model_name']}, Trees: {result['n_estimators']},
    Features: {result['num_selected_factors']}")
    Model: RandomForest_500trees, Trees: 500, Features: 2

    """
    return TrainRandomForestModelOutput(
        model_name="",
        n_estimators=0,
        max_depth=0,
        oob_r_squared=0.0,
        feature_importances=[],
        num_training_samples=0,
        num_selected_factors=0,
    )